### ISSUE TITLE
Labelpicker with Checkmk 2.20p5 - Failure in HW/SW inventory connector

### ISSUE THREAD

**Issue by kosasaga** [automation-monitoring/labelpicker#1]
In `./local/lib/python3/labelpicker/ds_plugins/lpds_hwswtree.py` the following module is imported:

`from cmk.gui.plugins.views import builtin_inventory_plugins`

In Checkmk 2.1.0 the import statement works as expected, in Checkmk 2.2.0 the import fails due to an unknown location

```
>>> from cmk.gui.plugins.views import builtin_inventory_plugins
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'builtin_inventory_plugins' from 'cmk.gui.plugins.views' (unknown location)
```

and Labelpicker stops working, rising an exception:

`🔴 Error importing datasource lpds_hwswtree`

Is there a workaround making Labelpicker work in Checkmk 2.2 or bugfix to apply?

Tested on:
Labelpicker 1.0.3
Checkmk 2.1.0p30 & 2.2.0p5

**Comment by PhilippLemke** [comment]
Thanks for the hint. I have removed the import, which for now was just a preparation for further versions, to get the displayhints.items dynamically. I have successfully tested the new version 1.0.4 with 2.2.0p1.
In 2.2.0p5 & p6 there seems to be a bug in the REST API activate changes call, which should be fixed by checkmk.
